name: ci dotnet

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: app

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET 5.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Display dotnet version
        run: dotnet --version
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal        
